# Site settings
title: "Ralitsa Voronevska's CV" 
description: Ralitsa Voronevska's CV
favicon: /assets/img/avatar.jpg
baseurl: /resume
url: https://ralitsavoronevska.github.io
rss_url: /pages/atom.xml


# Build settings
markdown: kramdown
highlighter: rouge
exclude: [vendor]

# Author settings
author:
  name: Ralitsa Voronevska
  title: Online Survey Programmer & Project Manager
  address: Sofia, Bulgaria
  email: ralicavoronevska@gmail.com
  link: https://ralitsavoronevska.github.io/about
  weibo:
  github: ralitsavoronevska
  linkedin: ralitsavoronevska123
  twitter: RVoronevska
  gavatar: /resume/assets/img/avatar.jpg
  stackoverflow: 6423505
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: cQuest Research & Consulting Ltd
      location: Sofia, Bulgaria
      title: Project Manager of QP Team
      started: May 2017
      duration: (May 2017 - March 2018)
      description: Technology used: HTML & CSS, JavaScript (+jQuery), XML, Python
    - work2:
      company: cQuest Research & Consulting Ltd
      location: Sofia, Bulgaria
      title: Java Developer
      started: July 2016
      duration: (July 2016 - May 2017)
      description: Technology used: HTML & CSS, JavaScript (+jQuery), and from November => XML and Python
    - work3:
      company: EPAM Systems Bulgaria Ltd
      location: Sofia, Bulgaria
      title: Technical Recruiter
      started: Dec 2015
      duration: (Dec 2015 - Apr 2016)
    - work4:
      company: EPAM Systems Bulgaria Ltd
      location: Sofia, Bulgaria
      title: Talent Acquisition Administrator
      started: May 2015
      duration: (May 2015 - Dec 2015)
    - work5:
      company: Easy Consult Ltd
      location: Varna, Bulgaria
      title: Junior HR Consultant
      started: Mar 2014
      duration: (Mar 2014 - Oct 2014)
    - work6:
      company: Polycontact OOD
      location: Varna, Bulgaria
      title: Trainee in the field of the Human Resources
      started: Feb 2014
      duration: (Feb 2014 - Mar 2014)
    - work7:
      company: Yepafrica B.V.
      location: Dordrecht, The Netherlands
      title: Trainee in the field of the Human Resources
      started: Sept 2013
      duration: (Sept 2013 - Dec 2013)
  educationHistory:
    - education1:
      organization: VFU "Chernorizetz Hrabar" University
      location: Varna, Bulgaria
      degree: Bachelor
      major: Bachelor in Informatics and computer technologies
      started: 29.09.2014
      duration: (29.09.2014 - 15.03.2015 (1 semester))
      description: GPA: - / -
    - education2:
      organization: VFU "Chernorizetz Hrabar" University
      location: Varna, Bulgaria
      degree: Master
      major: Master in Applied Psychology
      started: 15.09.2013
      duration: (15.09.2013 - 15.03.2015)
      description: GPA: 5.9 / 6
    - education3:
      organization: VFU "Chernorizetz Hrabar" University
      location: Varna, Bulgaria
      degree: Bachelor
      major: Bachelor in Psychology
      started: 15.09.2009
      duration: (15.09.2009 - 05.04.2013)
      description: GPA: 5.9 / 6
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: German
      proficiency: Intermediate
  programmingSkills:
    - skill1:
      name: HTML5
      percentage: 80%
    - skill2:
      name: CSS3
      percentage: 80%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: jQuery
      percentage: 70%
    - skill5:
      name: Bootstrap
      percentage: 70%
    - skill6:
      name: C#
      percentage: 50%
    - skill7:
      name: WordPress
      percentage: 50%
    - skill8:
      name: XML
      percentage: 40%
    - skill9:
      name: Python
      percentage: 40%

